packages:
  - packages/*
  - internal/*

catalog:
  '@eslint/js': ^10.0.1
  '@sinonjs/fake-timers': ^15.1.0
  '@types/node': ^24.10.13
  '@types/sinonjs__fake-timers': ^15.0.1
  '@typescript/native-preview': 7.0.0-dev.20260220.1
  eslint: ^10.0.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.5
  npm-run-all2: ^8.0.4
  prettier: ^3.8.1
  typescript: ^5.9.3
  typescript-eslint: ^8.56.0

shellEmulator: true
